name: .NET

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dotnet-version: ["6.0.x", "7.0.x", "8.0.x"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v1.1.1
              with:
                  versionSpec: "5.x"

            - name: Setup .NET ${{ matrix.dotnet-version }}
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ matrix.dotnet-version }}

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

            - name: Test
              run: dotnet test --configuration Release --no-build --verbosity normal

            - name: Pack and Combine
              run: |
                  dotnet pack --configuration Release --no-build -o ./nupkg/${{ matrix.dotnet-version }}
                  mkdir -p ./nupkg/combined
                  cp ./nupkg/${{ matrix.dotnet-version }}/*.nupkg ./nupkg/combined/

            - name: Push NuGet package to GitHub
              run: dotnet nuget push ./nupkg/combined/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GH_TOKEN }}
